## Introduction au traitement de langage humain
### 1
- On souhaite creer un parefeux capable de bloquer les mails ayant un contenu particuler ; cette procedure fait appel au traitement du langage naturel ou Naturel Langage Processing (NLP)
- Le NLP est la capacite pour un programme informatique de comprendre le langage humain telle qu'il est parlé ou écrit, il fait partit des technologie d'IA.

### 2 Exemple de programme utilisant le NLP 
- Le robot conversationel (ChatBot) ;
- L'analyse des mails pour la detection de spam ;
- La détection de virus ;
- La traduction automatique ;
-


### 3 Etape du NLP
Pour realiser un programme de NLP, nous avons besoin d'un echantillon de texte 
cet echantillon peut etre un echantillon de mail recu, des SMS, le contenu d'un livre etc 
Ensuite nous suivons les étapes ci-apres
- a : La tokenisation 
    - Elle consiste a convertir des caratere qui compose un texte en une liste de jeton. Lors de ce processus,
    on supprime :
        - Les ponctuations ;
        - Les mots fréquements utilisées (article , pronom , etc .. ) ; 
A la fin de cette étape on obtient la liste de token ou jeton

In [1]:
from nltk.corpus import stopwords

In [2]:
## Application de  la tokenisation 
texte = "Je suis allé le voir, lui et moi avons quitté Calavi pour Dassa"
## suppresion des ponctuations
import string 
texteOutPonctuation = [char for char in texte if char not in string.punctuation]


-  Elimination des stops words du test

In [3]:
text = ''
for text_ in texteOutPonctuation : text+=text_
clean_text = [word for word in text.split() if word.lower() not in stopwords.words('french')]
clean_text = ''.join(clean_text)

- La vectorisation  
Le principale probleme avec les jetons obtenu est qu'il sont des chaines de caracteres. Il nous faut les transformer en valeur numerque utilisable par les algorithmes.
Cela ce fais en trois etape en utilisant l'aproche bag-of-words

- ETAPE 1
Il s'agit de compter le nombre de fois qu'un mot apparait dans un test
Tf  = frquence du mot
Exemple ;
- Considérons un document contenant 100mots, dans lequel le mot chat =3 ;
chatFreq = 3/100

- ETAPE 2  INVERSE DOCUMENT FREQUENCY
    - il s'agit de ponderer les decomptes effecter precedement, de sorte que les jetons frquent obtiennent un poid inferieur
    - IDF = log((nombre total de texte)/(nombre total de text contenant le terme t )
)
- supposons que nous aayont 10 millions de texte et que le mot chat apparaissent dans 10 d'entre eux
- la frequence inverse de document est  : 
log(10000000/1000)\
- Ainsi le poids TF_IDF est le produits des quantités TF et IDF 

Application de la vectorisation :
Soit l'ensemnle de textes suivant

In [4]:
list_text = [
    "one geek helps two geeks" ,
    'two geeks help for geeks' ,
    'fach geek helps many other geeks at geeksforgeeks'
]

- Le modules CountVectorizer de la librairie scikit-learn est un exelent outil pour transformer du texte en vecteur sur la base de la frequence des mots qui apparent dans l'ensemble du texte.
- Ceci est utilie lorsque nous avons plusieurs texte et qu nous souhaitons convertir chaque mot de chaque texte en vecteur.

In [5]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

Vec = CountVectorizer()
Vec.fit(list_text)


CountVectorizer()

In [6]:
print(Vec.get_feature_names_out())
print(Vec.vocabulary_)

['at' 'fach' 'for' 'geek' 'geeks' 'geeksforgeeks' 'help' 'helps' 'many'
 'one' 'other' 'two']
{'one': 9, 'geek': 3, 'helps': 7, 'two': 11, 'geeks': 4, 'help': 6, 'for': 2, 'fach': 1, 'many': 8, 'other': 10, 'at': 0, 'geeksforgeeks': 5}


In [7]:
vec = Vec.transform(list_text) # valeurs adjuster

In [8]:
print(vec) ; 
# affichage de la matrce creuse
print(vec.toarray())

  (0, 3)	1
  (0, 4)	1
  (0, 7)	1
  (0, 9)	1
  (0, 11)	1
  (1, 2)	1
  (1, 4)	2
  (1, 6)	1
  (1, 11)	1
  (2, 0)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	1
  (2, 5)	1
  (2, 7)	1
  (2, 8)	1
  (2, 10)	1
[[0 0 0 1 1 0 0 1 0 1 0 1]
 [0 0 1 0 2 0 1 0 0 0 0 1]
 [1 1 0 1 1 1 0 1 1 0 1 0]]


Etape 3; Calcule des ponderation TF-IDF

In [9]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer()
tfidf.fit(vec)

tfidf = tfidf.transform(vec)
print(tfidf)

  (0, 11)	0.43306684852870914
  (0, 9)	0.5694308628404254
  (0, 7)	0.43306684852870914
  (0, 4)	0.33631504064053513
  (0, 3)	0.43306684852870914
  (1, 11)	0.3815187681027303
  (1, 6)	0.5016513317715935
  (1, 4)	0.5925667154413486
  (1, 2)	0.5016513317715935
  (2, 10)	0.3920626253314354
  (2, 8)	0.3920626253314354
  (2, 7)	0.298173732156414
  (2, 5)	0.3920626253314354
  (2, 4)	0.23155850231624595
  (2, 3)	0.298173732156414
  (2, 1)	0.3920626253314354
  (2, 0)	0.3920626253314354


In [10]:
feature_names = Vec.get_feature_names_out()
list_vector = pd.DataFrame(tfidf.T.todense() , index=feature_names,columns=['TFIDF-T1','TFIDF-T2',"TFIDF-T3"])
print(list_vector)

               TFIDF-T1  TFIDF-T2  TFIDF-T3
at             0.000000  0.000000  0.392063
fach           0.000000  0.000000  0.392063
for            0.000000  0.501651  0.000000
geek           0.433067  0.000000  0.298174
geeks          0.336315  0.592567  0.231559
geeksforgeeks  0.000000  0.000000  0.392063
help           0.000000  0.501651  0.000000
helps          0.433067  0.000000  0.298174
many           0.000000  0.000000  0.392063
one            0.569431  0.000000  0.000000
other          0.000000  0.000000  0.392063
two            0.433067  0.381519  0.000000


In [11]:
list_vector = list_vector.sort_values(by=["TFIDF-T1"] , ascending=False)
list_vector

TFIDF-T1  TFIDF-T2  TFIDF-T3
one            0.569431  0.000000  0.000000
geek           0.433067  0.000000  0.298174
helps          0.433067  0.000000  0.298174
two            0.433067  0.381519  0.000000
geeks          0.336315  0.592567  0.231559
at             0.000000  0.000000  0.392063
fach           0.000000  0.000000  0.392063
for            0.000000  0.501651  0.000000
geeksforgeeks  0.000000  0.000000  0.392063
help           0.000000  0.501651  0.000000
many           0.000000  0.000000  0.392063
other          0.000000  0.000000  0.392063

LA NORMALISATION :
il s'agit de normaliser des vecteur a la longueur pour faire abstraction de la longuer  du texte d'origine (norme 12)